- pacman:
  - neovim
  - feh    
  - zsh
  - xclip
  - python-pywal
  - wget
  - picom
  - alsa-utils
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - tree
  - zathura
  - zathura-pdf-poppler
  - redshift
  - sxiv
  - ranger
  - nemo
  - ctags
  - playerctl
  - zip
  - python-pip
  - nodejs
  - fzf
  - light
  - man
  - bluez-utils
  - npm
  - noto-fonts-emoji
  - thunderbird
  - pavucontrol
- pacaur:
  - xorg-xrandr
  - polybar
  - siji-git
  - ttf-font-awesome-4
  - ttf-font-awesome-5
  - nerd-fonts-inconsolata
  - gitkraken
  - ttf-monaco
  - brave-bin
