- defaults:
    yum:
        options: "-q -y"
        stdout: False
        stderr: True
        sudo: True
- shell:
  - [curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -,  Add nodejs repo to yum]
- yum:
  - make
  - gcc-c++
  - nodejs
  - neovim
  - zsh
