- defaults:
    link:
      create: true
      relink: true
      force: true
- clean:
  - "~/.config/nvim/"
- link:
    "~/.config/nvim/UltiSnips": editors/nvim/snippets
    "~/.config/nvim/init.vim": editors/nvim/init.vim
    "~/.config/nvim/coc-settings.json": editors/nvim/coc-settings.json
    "~/.local/share/nvim/site/autoload/plug.vim": editors/nvim/plug.vim
- shell:
  - [pip install --user neovim,  Installing Python 3 NeoVim plugin]
  - [nvim -c 'PlugClean!' -c 'PlugInstall' -c 'PlugUpdate' -c 'q' -c 'q', Installing nvim plugins]
  - [nvim -c 'CocInstall coc-eslint' , Installing  coc eslint]
  - [npm install -g neovim,  Installing Nodejs NeoVim plugin]

