- defaults:
    link:
      create: true
      relink: true
      force: true
- link:
    "~/.zshrc": shells/zsh/zshrc
    "~/.oh-my-zsh": shells/zsh/ohmyzsh
    "~/.oh-my-zsh/custom/themes/synergy.zsh-theme": shells/zsh/themes/synergy.zsh-theme

