- defaults:
    link:
      create: true
      relink: true
      force: true
    yum:
      options: "-q -y"
      stdout: True
      stderr: True

- clean:
  - "~"
  - "~/.config"
- shell:
  - [git submodule update --init --recursive, Installing submodules]
