#!/bin/bash
AUR=https://aur.archlinux.org

PACMAN_PACKAGES=(  
	xorg-xrandr 
	feh    
	zsh
	xclip
	python-pywal
	wget
	picom
	alsa-utils
	pulseaudio
	pulseaudio-alsa
	pulseaudio-bluetooth
	tree
	zathura
	zathura-pdf-poppler
	redshift
	sxiv
	ranger
	nemo
	ctags
	rxvt-unicode
	urxvt-perls
	playerctl
	zip
	python-pip
)
AUR_PACKAGES=( 
	polybar 
	brave-bin
	siji-git
	ttf-font-awesome-4
	compton-tryone-git
	nerd-fonts-inconsolata
	urxvt-resize-font-git
)

# python3 -m pip install --user --upgrade pynvim # for vim python plugins

# Install pacman packages
sudo pacman -S --noconfirm ${PACMAN_PACKAGES[@]}

# Install AUR packages
for package in ${AUR_PACKAGES[@]}
do
	echo $AUR/$package.git
	git clone $AUR/$package.git /tmp/$package
	cd /tmp/$package
	makepkg -sri --noconfirm
done

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# Install vim-plug
sh -c "$(curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)"


